# Generated by Django 4.2.5 on 2023-09-20 16:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="last_name",
            new_name="description",
        ),
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="avatars/"),
        ),
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
