# Generated by Django 4.2.5 on 2023-09-28 03:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0002_follower"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Follower",
        ),
    ]
