# Generated by Django 4.2.5 on 2023-09-18 17:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="posts",
            old_name="cat",
            new_name="user",
        ),
    ]
