# Generated by Django 4.2.5 on 2023-09-27 06:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="posts",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
