# Generated by Django 4.2.5 on 2023-09-19 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_rename_cat_posts_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
