# Generated by Django 4.2.5 on 2023-09-27 12:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0002_alter_posts_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="posts",
            name="categories",
        ),
        migrations.AlterField(
            model_name="posts",
            name="title",
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name="posts",
            name="categories",
            field=models.ManyToManyField(to="post.category"),
        ),
    ]
