# Generated by Django 4.2.5 on 2023-09-19 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_posts_is_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='is_favorite',
        ),
        migrations.DeleteModel(
            name='FavoritePost',
        ),
    ]
