# Generated by Django 4.2.5 on 2023-09-21 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_remove_posts_is_favorite_delete_favoritepost'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='categories',
            field=models.CharField(blank=True),
        ),
    ]
