# Generated by Django 4.2.5 on 2023-09-21 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_posts_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='categories',
            field=models.CharField(),
        ),
    ]
