# Generated by Django 4.2.5 on 2023-09-26 07:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0008_alter_posts_categories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="posts",
            name="file_video",
            field=models.FileField(blank=True, upload_to="videos/"),
        ),
    ]
