# Generated by Django 4.2.5 on 2023-09-25 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rivew', '0002_alter_comment_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
