# Generated by Django 4.2.4 on 2023-09-26 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='follower',
            new_name='friends',
        ),
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='following',
        ),
    ]
