# Generated by Django 4.2.4 on 2023-09-26 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscriptions', '0002_rename_follower_subscription_friends_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='friends',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends_subscriptions', to=settings.AUTH_USER_MODEL),
        ),
    ]
