# Generated by Django 4.2.4 on 2023-09-26 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_alter_subscription_friends'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='friends',
            new_name='follower',
        ),
        migrations.AddField(
            model_name='subscription',
            name='friend_email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
